

public enum MessageBusType
{
    NONE,
    LevelStart,
    LevelEnd,
    PlayerPosition,
    PointAdded,
    LogedintoServer,
    LogedOutServer,
    FinishGetInfoFacebook,
    FinishSyncLevelRanking,
    FailSyncLevelRanking,
    UserDataChanged,
    FacebookLoginFailed,
    OnDefeatedFriends,
	OnDefeatedFriendsInSongs,
    LogedinFBIsNew,
    MenuBtnLeaderBoardClick,
    LevelRankingClick,
    LoginParseFailed,
    //GameDataChanged,

    XPChanged,
    LifeChanged,
	DiamondChanged,
    DiamondChangedDelayForMenuShow,
    CoinChanged,
    UserLevelChanged,
    UserPlayRecordChanged,
    TimeLifeCountDown,
	TimeDiscountVippassCountDown,
    FacebookUserDataReceived,
    IAPManagerInitializeFailed,
    PurchaseFailed,
	PurchaseRemoveAdsFailed,
    ProductPurchased,
    NativeAdItemLoaded,
    LanguageChanged,
    NativeAdItemFailedToLoad,
    CompletedIAPLocalization,
    OnSelectedOrUnselectedInviteFriend,
    //CompletedLevelRanking,
    OnCompletedGetGeoLocation,
    CompletedPostStatusShareFacebook,
    CancelPostStatusShareFacebook,
	PostingToFacebook,
    OnCompletedRestoreApple,
    PlaySongAction,
	OnClaimQuest,
	OnMoveMenu,
	CanMoveMenu,
    OnBuySong,

    //for online event
    Evt_Room_Join_Status = 201,// when waiting another person in room
    Evt_Room_MoveTo_Gameplay = 202,// start room
    Evt_Room_Sync_Status = 203,// when waiting another download this song
    Evt_Room_Error_To_Play = 204,// when room can not start due to error
    Evt_Room_Ready_To_Play = 205,// when room ready to start(all person ready or time to go)
    Evt_Room_Finish = 206,// when room end
    Evt_SyncBehaviorToRoom = 207,// when user sync behavior
    Evt_Room_Chat = 208,// when a person chat in waiting start room
    Evt_Kick_out = 209,// kick user violate (hack, cheat, timeout...)  
	Evt_Tour_Join_Status = 210,// when waiting join tournament
	Evt_Set_Auto_Mode = 211,//set auto mode
	Evt_UpdateRoomInfo = 212,//set auto mode
    Evt_HasError = 1000,
    Evt_Online_Disconnect = 2000,
    OnMeDieOnline,
	ResetSongsList,
	OnPlayPreview,
	OnStopPreview,
	OnProgressPreview,
	FailToLoadPreview,
	UnlockSongWithVideo,
    SharedForAnalytic,
	PlayEffectShopBuySong,
	ButtonCallBack,
	GachaKeyChange,
	RewardForContinueGame,
    RewardRubyCount,
	ActionPhaseBG,
    ChangeTilesThems,
    finishInitThemes,
	ChartNotifySale,
    DataQuestPopularChange,
    ClaimLevelReward,
    fullET,
    BuySongPackByET,
    OnChangePopular,
    TrialSong,
    VideoAdsRewarded,
    ShowRewardTimeOut,
    ShowRewardFail,
    RewardClose,
    VipPassPurchased,
    VipPassProcessDone,
    OnPurchasedAlbum,
    OnConflictDataPopupClosed,
    TicketsChanged,
    SpecialSongRewarded,
    LocalSongDataChanged,
    FavoriteChanged,
    WatchRewardAdsToPlayEndless,
    VipSubscriptionPurchased,
    SongPackPurchased,
    WaitForInitAllSong,
    PlayerDataSyncFinished,
    SyncLineChanged,
    X2GiftBox,
    UnlockSelectionThemeV2,
    DonePredownloadSong,
    OnFailedRestoreApple,
    OnPopupClose,
    SongRecommendPlayed,
    RefreshSongListRecommend,
    OnClickDailyMixTab,
    OnRefreshUI,
    OnChangeScene,
    // event for Battle Mode Ranking
    GetSeasonData,
    GetTop100,
    GetUserRank,
    GetUserSeason,
    GetUserSeasonReward,
    SetUserAvatar,
    MenuBtnSettingClick,
    ProfileSettingClose,
    UserProfileClose,
    OnRefreshSonglist,
    ProfileLeaderboardOpen,
    OnGotRewardadsByVip,
    ToggleActiveHomeBtn,
    CallUserProfileShareFacebook,
    ChangeNumberNotification,
    VipPassByDay,
    ChestRankingTap,
    WaitingAdsCallback,
    WaitingAdsCancel,
    InhouseVideoAdsShown,
    RoomPasswordDay,
    SongChangeDay,
    DropItemSelected,
    ActiveVipPassByDay,
    OnMinPassAmazon,
    AmazonClaimReward,
    LinkAccountChanged,
    LockSwapMainMenu,
    SetMainMenuState,
    OnChangeSceneType,
    SetSceneType,
    CloseMergeScene,
    OnDiscoverySearch,
    OnMergeSceneShowLoading,
    OnFinishChangeScene,
    OnHideMergeSceneUI,
    OnShowMergeSceneUI,
    OnTabSongListChanged,
    JumpToDiscovery,
    ShowCategory,
    ResultSongSuggestion,
    SplashSceneInited,
    SplashSceneClose,
    RefreshBannerPI,
    FeverModeColor,
    TopBannerStatus,
    MoodChange,
    MoodChangeFinished,

    DifficultyChange,
    NewSequentialForceUpdateHome,
    ForceReloadOnboardingSong,
    OnBtnResumeClicked,

    MissionValueChanges,
    MissionUIUpdate,
    InformUnlockSequentialFeature,
    ShowOnboardingEnergy,
    MinusEnergy,
    EnergyBalanceChanges,
    OnGamePlayInitCompleted,
    
    SliderChangeLane,
    TileOutOfScreen,
    TileClearStageHit,
    RecentlyPlayedChange,
    OnPerfectTap,
    OnCloseAPOnboarding,
    OnOpenAPOnboarding,
    OnSendReviveProgressData,
    OnPerfectTapReleased,
    OnGameContinue,
    OnReviveVideoAdSuccess,
    OnGamePlayPause,
    OnChangeGameStage,
    OnGameStart,
    LedFadeChange,
    LedShineChange,
    OnLedEventSetupFinish,
    OnTileTap
}